let questions = [
    {
        image: "assets/Q13.png",
        question: 'The album name?',
        choice1: 'Mr. Wonderful',
        choice2: 'Rumours',
        choice3: 'Tango in the Night',
        answer: 2,
    },
    { 
        image: "assets/Q5.png",
        question: 'The album name?',
        choice1: 'Sticky fingers',
        choice2: 'Emotional Rescue',
        choice3: 'Black and Blue',
        answer: 1,
    },
    {
        image: 'assets/Q5.png',
        question: 'The author?',
        choice1: 'Led Zeppelin',
        choice2: 'The Who',
        choice3: 'The Rolling Stones',
        answer: 3,
    },
    {
        image: "assets/Q2.jpg",
        question: 'The album name?',
        choice1: 'Abby Road',
        choice2: 'Abbey Road',
        choice3: 'Abey Road',
        answer: 2,
    },
    {
        image: "assets/Q2.jpg",
        question: 'The author?',
        choice1: 'Beatles',
        choice2: 'The Strokes',
        choice3: 'Led Zeppelin',
        answer: 1,
    },
    {
        image: "assets/Q11.png",
        question: 'The author?',
        choice1: 'The Velvet Underground',
        choice2: 'Andy Warhol',
        choice3: 'The Velvet Underground & Nico',
        answer: 3,
    },
    {
        image: "assets/Q10.jpg",
        question: 'The author?',
        choice1: 'Joy Division',
        choice2: 'Arctic Monkeys',
        choice3: 'The Velvet Underground',
        answer: 1,
    },
    {
        image: "assets/Q1.jpg",
        question: 'The album name?',
        choice1: 'AM',
        choice2: 'Suck it and See',
        choice3: 'The Car',
        answer: 1,
    },
    {
        image: "assets/Q7.png",
        question: 'The author?',
        choice1: 'Bryan Adams',
        choice2: 'Lenny Kravitz',
        choice3: ' Bruce Springsteen',
        answer: 3,
    },
    {
        image: "assets/Q3.jpg",
        question: 'The author?',
        choice1: 'Pink Floyd',
        choice2: 'Led Zeppelin',
        choice3: 'The Who',
        answer: 2,
    },
    {
        image: "assets/Q8.png",
        question: 'The author?',
        choice1: 'The Clash',
        choice2: 'Sex Pistols',
        choice3: 'The Rolling Stones',
        answer: 1,
    },
    {
        image: "assets/Q9.png",
        question: 'The album name?',
        choice1: 'Yellow Submarine',
        choice2: "A Hard Day's Night",
        choice3: "Sgt Pepper’s Lonely Hearts Club Band",
        answer: 3,
    },
    {
        image: "assets/Q4.png",
        question: 'The album name?',
        choice1: 'Nevermind',
        choice2: 'In Utero',
        choice3: 'Bleach',
        answer: 1,
    },
    {
        image: "assets/Q6.png",
        question: 'The author and the album name?',
        choice1: 'Fletwood Mac - Fleetwood Mac',
        choice2: 'Beatles - The Beatles (White Album)',
        choice3: 'Pink Floyd - The Wall',
        answer: 2,
    },
    {
        image: "assets/Q12.png",
        question: 'The author and the album name?',
        choice1: 'Pink Floyd - The Division Bell',
        choice2: 'Pink Floyd - The Wall',
        choice3: 'Pink Floyd - The Dark Side of the Moon',
        answer: 3,
    },
    {
        image: "assets/Q14.png",
        question: 'The author?',
        choice1: 'The Smiths',
        choice2: 'The Cure',
        choice3: 'Talking Heads',
        answer: 1,
    },
    {
        image: "assets/Q15.png",
        question: 'The author?',
        choice1: 'Nine Inch Nails',
        choice2: 'Green Day',
        choice3: 'Good Charlotte',
        answer: 2,
    },
    {
        image: "assets/Q16.png",
        question: 'The author?',
        choice1: 'Pixies',
        choice2: 'Radiohead',
        choice3: 'Weezer',
        answer: 3,
    },
    {
        image: "assets/Q17.png",
        question: 'The author?',
        choice1: 'Sum 41',
        choice2: 'Blink-182',
        choice3: 'Good Charlotte',
        answer: 2,
    },
    {
        image: "assets/Q18.png",
        question: 'The album name?',
        choice1: 'Back to Black',
        choice2: 'Violet',
        choice3: 'Frank',
        answer: 1,
    },
    {
        image: "assets/Q19.png",
        question: 'The album name?',
        choice1: 'A Moon Shaped Pool',
        choice2: 'Amnesiac',
        choice3: 'Kid A',
        answer: 3,
    },
    {
        image: "assets/Q20.png",
        question: 'The author?',
        choice1: 'Blondie',
        choice2: "The Go-Go's",
        choice3: 'Cyndi Lauper',
        answer: 1,
    },
    {
        image: "assets/Q21.png",
        question: 'The author?',
        choice1: 'Audioslave',
        choice2: "Pearl Jam",
        choice3: 'Foo Fighters',
        answer: 3,
    },
    {
        image: "assets/Q22.png",
        question: 'The author?',
        choice1: 'Bob Dylan',
        choice2: 'Neil Young',
        choice3: 'Bruce Springsteen',
        answer: 1,
    },
    {
        image: "assets/Q23.png",
        question: 'The author?',
        choice1: 'Aerosmith',
        choice2: 'AC/DC',
        choice3: 'Ozzy Osbourne',
        answer: 2,
    },
    {
        image: "assets/Q24.png",
        question: 'The album name?',
        choice1: 'Back in Black',
        choice2: 'The Razors Edge',
        choice3: 'Black Ice',
        answer: 1,
    },
    {
        image: "assets/Q25.png",
        question: 'The author?',
        choice1: 'The Cure',
        choice2: 'Joy Division',
        choice3: 'Christian Death',
        answer: 1,
    },
    {
        image: "assets/Q26.png",
        question: 'The author?',
        choice1: 'Billy Joel',
        choice2: 'Elton John',
        choice3: 'Rod Stweart',
        answer: 2,
    },
    {
        image: "assets/Q27.png",
        question: 'The author?',
        choice1: 'The Clash',
        choice2: 'Sex Pistols',
        choice3: 'The Ramones',
        answer: 3,
    },
    {
        image: "assets/Q28.png",
        question: 'The album name?',
        choice1: 'Hot Space',
        choice2: 'News of the World',
        choice3: 'Queen II',
        answer: 3,
    },
    {
        image: "assets/Q28.png",
        question: 'The author?',
        choice1: 'Deep Purple',
        choice2: 'Queen',
        choice3: 'Led Zeppelin',
        answer: 2,
    },
]

export default questions;

console.log(questions.length)